modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-echoes"
#logoFile = "logo.png"
authors = "FTB Team"
description = '''
Description
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${mod_loader_range}"
ordering = "NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "magic_coins"
mandatory = true
versionRange = "[1.0.9,)"
ordering = "NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
mandatory = true
versionRange = "[9.4.2,)"
ordering = "NONE"
side="BOTH"
